### ISSUE TITLE
Feat: 헤더 및 페이지 레이아웃 개발

### ISSUE THREAD

**Issue by leewooseong** [tripsketcher/TripSketcher#1]
# 헤더 및 페이지 레이아웃 개발

## Description
- 페이지 헤더 및 프로젝트 레이아웃을 개발합니다.

## Todo

- [x] 헤더 컴포넌트 만들기
- [x] 반응형 적용해서 모바일 헤더로 적용하기
- [x] 회원 가입 및 로그인 버튼 만들기
- [x] routing 기능 적용
- [x] Default Page 설정
