### ISSUE TITLE
Feat: 로그인 & 로그아웃 기능 개발 

### ISSUE THREAD

**Issue by leewooseong** [tripsketcher/TripSketcher#3]
# 로그인 & 로그아웃 기능 개발 

## Description

로그인 및 로그아웃 기능 개발 

## Todo

- [x] 로그인 페이지 작성
- [x] zustand 적용해서 유저 정보 전역에서 관리하기
- [ ] 페이지 필터링 레이아웃 개발
- [ ] 로그인 및 로그 아웃 api 개발
- [ ] 로그아웃 시 api 요청 후 사용자 정보 비워주기
- [ ] 로그인 및 로그아웃 할 경우 요청 성공 이후 요청을 수행하기 전 페이지로 돌아가야한다.(단, 로그아웃 시 권한이나 인증 페이지가 없다면 default 페이지로 이동)
- [ ] 헤더에 사용자 정보에 따라 표시 다르게 해주기
- [ ] 인증 요청 api의 결과로 권한 없음 응답을 받을 경우 사용자 정보 null로 처리해주기
- [ ] OAuth 적용하기 - kakao

## Caution
- Default Page 및 헤더의 경우 사용자 인증 정보를 직접적으로 사용하지 않지만 인증 정보 여부에 따라서 UI를 다르게 표시해 주어야한다.
- 이를 위해서 권한 없음 응답을 받거나, 로그아웃할 때는 꼭 전역으로 관리하는 유저 정보를 제거해주어야 한다.
- 로그인 로그아웃 api를 이용할 경우 이전 페이지를 유지하기 위해선 api 수행하는 곳에 이전 url을 넘겨줘서 다시 그쪽으로 이동시키는게 더 합리적인 방법일 수 있다.(일력의 과정을 hooks로 빼두는 것도 좋을 듯!)
